import "@/styles/globals.css";
import { Inter } from "next/font/google";

export const fetchCache = "force-no-store";
export const dynamic = "force-dynamic";
export const revalidate = 0;

const inter = Inter({
   subsets: ["latin"],
});

export const metadata = {
   title: "Space Travel",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={inter.className}>{children}</body>
      </html>
   );
}
