import "@/styles/globals.css";
import { Inter } from "next/font/google";

export const dynamic = "force-dynamic";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Space Travel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
